baseURL: "https://www.michalsramek.eu"
languageCode: "en-us"
title: "Michal Šrámek"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"
    
Paginate: 3
enableRobotsTXT: true

markup:
  goldmark:
    renderer:
      unsafe: true

# Menus:
#   main:
#     # - identifier: blog
#     #   name: Blog
#     #   title: Blog posts
#     #   url: /blogs
#     #   weight: 1
#     # - identifier: gallery
#     #   name: Gallery
#     #   title: Blog posts
#     #   url: /gallery
#     #   weight: 2
#     #Dropdown menu
#     - identifier: dropdown
#       title: Main menu
#       name: Menu
#       weight: 1
#     - identifier: dropdown1
#       title: example dropdown 1
#       name: example 1
#       url: /#
#       parent: dropdown
#       weight: 1
#     - identifier: dropdown2
#       title: example dropdown 2
#       name: example 2
#       url: /#
#       parent: dropdown
#       weight: 2

params:
  title: "Michal Šrámek"
  description: "AUTHOR. SCIENTIST. INVENTOR"
  # staticPath: ""  # The path to serve the static files from
  favicon: "/favicon.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    disableThemeToggle: false
    defaultTheme: "dark" # light

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    brandName: " " # Brand name for the brand | default is the title variable
    disableSearch: true
    menus:
      disableAbout: true
      disableExperience: true
      disableEducation: true
      disableProjects: true
      disableAchievements: true
      disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hi, welcome to my page! My name is"
    title: "Michal."
    subtitle: "AUTHOR. SCIENTIST. INVENTOR"
    content: |-
      Passionate scientist working with cutting-edge information technologies, while also serving as the founder of several small businesses.
    image: /images/hero.jpg
    socialLinks:
      fontAwesomeIcons:
        # - icon: fab fa-linkedin
        #   url: https://example.com
        # - icon: fab fa-facebook
        #   url: https://example.com
        # - icon: fab fa-github
        #   url: https://github.com/sramekmichal
        # - icon: fab fa-google
        #   url: https://scholar.google.com/citations?user=o1_64h8AAAAJ&hl=cs
        # - icon: fab fa-researchgate
        #   url: https://example.com
        
      customIcons:
        # - icon: /fav.png
        #   url: "https://example.com"

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/me.jpg"
    content: |-
      I am an experienced IT professional with a background in biochemistry and a passion for cloud development. I maintain a strong enthusiasm for science, technology, and art. Currently, I hold the position of Automation Engineer at [Alma Career Czechia](https://www.almacareer.com/cz/en) in Prague, CZ.
      
      I am open minded person adapted to problem solving with attention to details.
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "Kubernetes"
        - "Go"
        - "Typescript"
        - "AWS"
        - "GitHub"
        - "Python"
        - "SQL"
        - "Helm"

  # Experience
  experience:
    enable: true
    title: "Latest Occupation"
    items:
      - job: "Automation Engineer"
        company: "Alma Career Czechia"
        companyUrl: "https://www.almacareer.com/cz/en"
        date: "Sep 2019 - present"
        featuredLink:
          enable: true
          name: "VISIT COMPANY"
          url: "https://www.almacareer.com/cz/en"
        content: |-
          Department of Developers Experience (previously Architecture) at [Alma Career Czechia](https://www.almacareer.com/cz/en) in Prague, CZ.
          
          -  Responsible for the Nomad-release, Kubernetes initiator and managing the GitHub Organization for Enterprise needs, including AWS integration with a deeper focus on security.
      
      # - job: "Research Assistant"
      #   company: "Genome Dynamics"
      #   companyUrl: "https://www.img.cas.cz/en/"
      #   date: "Jan 2019 - Aug 2019"
      #   featuredLink:
      #     enable: true
      #     name: "VISIT INSTITUTE"
      #     url: "https://www.img.cas.cz/en/"
      #   info:
      #     enable: true
      #     content: Laboratory of Genome Dynamics
      #   content: |-
      #     I was part of department of Genom Dynamics of Dr. Keith Caldecott from Sussex Unversity at [IMG of the CAS](https://www.img.cas.cz/group/hana-hanzlikova/).
          
      #     - Participation in grant projects (identification of novel regulators of PARP1/XRCC1 proteins).

      # - job: "Laboratory Manager"
      #   company: "Genome Integrity"
      #   companyUrl: "https://www.img.cas.cz/en/"
      #   date: "Jan 2012 - Dec 2018"
      #   featuredLink:
      #     enable: true
      #     name: "VISIT INSTITUTE"
      #     url: "https://www.img.cas.cz/en/"
      #   info:
      #     enable: true
      #     content: Laboratory of Genome Integrity
      #   content: |-
      #     I was part of department of Genome Integrity of Dr. Jiří Bártek at [IMG of the CAS](https://www.img.cas.cz/group/zdenek-hodny/).
          
      #     - participation in grant projects (theranostic nanomedicine)
      #     - management of department.
  
  # Education
  education:
    enable: true
    title: "Latest Education"
    index: false
    items:
      - title: "Doctoral Study"
        school:
          name: "Czech University of Life Sciences"
          url: "https://www.af.czu.cz/en"
        date: "2023 - present"
        study: "Chemistry"
        thesis: "Synthesis of selenium and biochar nanoparticles and their benefit to agricultural applications"
        featuredLink:
          enable: false
          name: "Read Online"
          url: ""
        content: |-
            - <u>Educational Field:</u> Physical Sciences

      # - title: "Master of Science"
      #   school:
      #     name: "Czech University of Life Sciences"
      #     url: "https://www.af.czu.cz/en"
      #   date: "2021 - 2023"
      #   study: "Conservation and Use of Natural Resources"
      #   thesis: "Analysis of Biofuels from Waste Lignocellulosic Materials by Gas Chromatography"
      #   featuredLink:
      #     enable: true
      #     name: "Read Online"
      #     url: "https://dx.doi.org/10.13140/RG.2.2.28356.81283"
      #   content: |-
      #       - <u>Educational Field:</u> Natural Sciences

      # - title: "Bachelor of Science"
      #   school:
      #     name: "University of South Bohemia"
      #     url: "https://www.zsf.jcu.cz/en/"
      #   date: "2016 - 2019"
      #   study: "Medical Laboratory Technican"
      #   thesis: "Interaction of Gold Cationic Nanoparticles with Blood Cells and Their Distribution in the Model Organism"
      #   featuredLink:
      #     enable: true
      #     name: "Read Online"
      #     url: "https://doi.org/10.13140/RG.2.2.34534.09288"
      #   content: |-
      #       - <u>Educational Field:</u> Healthcare

      # - title: "High School Diploma"
      #   school:
      #     name: "Schola Humanitas"
      #     url: "https://www.humanitas.cz/"
      #   date: "2008 - 2012"
      #   study: "Protection and Restoration of the Environment"
      #   thesis: "Malacocenosis Fossil Research from Cretaceous Period and Geochemistry at the Undescribed Place"
      #   featuredLink:
      #     enable: true
      #     name: "Read Online"
      #     url: "https://doi.org/10.13140/RG.2.2.26145.48484"
      #   content: |-
      #       - <u>Educational Field:</u> Life Sciences

  # projects
  projects:
    enable: true
    title: "My Family"
    items:
      - title: Aperta Studio
        content: Business website related to consulting, model designing and custom 3D printing. I work with various FDM printers and one MSLA.
        image: /images/projects/apertastudio.png
        featured:
          name: Ask for Services
          link: https://www.apertastudio.eu/
        badges:
          - "3D"
          - "Design"
          - "Crafting"
        links:
          - icon: fab fa-linkedin
            url: https://www.linkedin.com/company/apertastudio
          - icon: fab fa-facebook
            url: https://www.facebook.com/apertastudio
          - icon: fa fa-envelope
            url: mailto:sramek.consulting@aol.com

      - title: NERDSHARK
        content: E-shop with mostly my personal fashion and art goods. My goal is to turn the site into something more than an e-shop, but more like a community of artists.
        image: /images/projects/nerdshark.png
        featured:
          name: Visit E-shop
          link: https://www.nerdshark.eu
        badges:
          - "Fashion"
          - "Art"
          - "HomeMade"
        links:
          - icon: fab fa-linkedin
            url: https://www.linkedin.com/company/nerdshark
          - icon: fab fa-facebook
            url: https://www.facebook.com/nerdsharkshop
          - icon: fa fa-envelope
            url: mailto:info@nerdshark.eu

# Achievements
  achievements:
    enable: true
    title: "Latest Achievements"
    items:
      - title: Creative Skills for Innovation
        content: New Generation of Founders - A Grow with Google PROGRAMME (2022).
        url: "/images/google-csi.jpg"
      - title: Go Programming Language
        content: "Udemy Certificate of Completion - Learn How to Code (2020)"
        url: "/images/udemy-go.jpg"
      - title: 1st Place in Poster Contest
        content: NANOCON 9th International Conference on Nanomaterial - Research & Application (2017).
        url: https://www.nanocon.eu/en/
      # - title: Microsoft Imagine Runner
      #   content: We are developed a product which can help others.
      # - title: Google Summer of Code
      #   content: Contributed to a open source project.
      #   url: https://example.com

  #Contact
  contact:
    enable: true
    title: "Get in Touch"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: ""
    btnName: Mail me
    formspree:
      enable: true # `contact.email` value will be ignored
      formId: xoqzvzvl # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
      emailCaption: "Enter your email address"
      messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "blogs"
      count: 0
      title: Recent Posts
      enable: false
      disableFeaturedImage: true
    socialNetworks:
      linkedin: https://www.linkedin.com/in/michal-sramek
      facebook: https://www.facebook.com/michal.sramek5
      github: https://github.com/sramekmichal
      scholar: https://scholar.google.com/citations?user=o1_64h8AAAAJ&hl=cs
      researchgate: https://www.researchgate.net/profile/Michal-Sramek

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false
    
  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true
